NaseSlovoApp/Controllers/SubscriptionController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using NaseSlovoApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace NaseSlovoApp.Controllers
{
    public class SubscriptionController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();
        private ApplicationSignInManager _signInManager;

        /// <summary>
        /// Application DB context
        /// </summary>
        protected ApplicationDbContext ApplicationDbContext { get; set; }

        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        protected UserManager<ApplicationUser> UserManager { get; set; }

        public SubscriptionController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Subscription
        public ActionResult Index()
        {
            return View();
        }


        // GET: Subscription/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Subscription/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Subscription/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Subscription/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Subscription/Delete/5
        public ActionResult Delete(int id)
        {
            return RedirectToAction("Index");
        }

        // GET
        public ActionResult AuthorSub()
        {
            // TODO posalji model authori aslist
            var autori = db.Korisnici.Where(t => t.Autor==true);
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            var tmp = korisnik.Pretplaceni.ToList();
            List<int> pretplaceni = new List<int>();
            foreach(Korisnik k in tmp)
            {
                pretplaceni.Add(k.KorisnikID);   
            }
            ViewBag.pret = pretplaceni;
            return View(autori.ToList());
        }

        // POST
        [HttpPost]
        public ActionResult AuthorSub(Korisnik autor)
        {
            var autorID = Request.Form.Get("KorisnikID");
            autor = db.Korisnici.Find(Int32.Parse(autorID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Autori.Add(autor);
                db.SaveChanges();
            }
            return RedirectToAction("AuthorSub");
        }
        [HttpPost]
        public ActionResult CancelAuthor()
        {
            var autorID = Request.Form.Get("KorisnikID");
            Korisnik autor = db.Korisnici.Find(Int32.Parse(autorID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Autori.Remove(autor);
                db.SaveChanges();
            }
            return RedirectToAction("AuthorSub");
        }

        public ActionResult TypeSub()
        {
            var vrste = db.Vrste;
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            var tmp = korisnik.Vrste.ToList();
            List<int> pretplaceni = new List<int>();
            foreach (Vrsta k in tmp)
            {
                pretplaceni.Add(k.VrstaID);
            }
            ViewBag.pret = pretplaceni;
            return View(vrste.ToList());
        }

        [HttpPost]
        public ActionResult TypeSub(Vrsta v)
        {
            var vrstaID = Request.Form.Get("VrstaID");
            Vrsta vrsta = db.Vrste.Find(Int32.Parse(vrstaID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Vrste.Add(vrsta);
                db.SaveChanges();
            }
            return RedirectToAction("TypeSub");
        }

        [HttpPost]
        public ActionResult CancelType()
        {
            var vrstaID = Request.Form.Get("VrstaID");
            Vrsta vrsta = db.Vrste.Find(Int32.Parse(vrstaID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Vrste.Remove(vrsta);
                db.SaveChanges();
            }
            return RedirectToAction("TypeSub");
        }


        public ActionResult ThemeSub()
        {
            var teme = db.Teme;
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            var tmp = korisnik.Teme.ToList();
            List<int> pretplaceni = new List<int>();
            foreach (Tema k in tmp)
            {
                pretplaceni.Add(k.TemaID);
            }
            ViewBag.pret = pretplaceni;
            return View(teme.ToList());
        }

        [HttpPost]
        public ActionResult ThemeSub(Tema t)
        {
            var temaID = Request.Form.Get("TemaID");
            Tema tema = db.Teme.Find(Int32.Parse(temaID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Teme.Add(tema);
                db.SaveChanges();
            }
            return RedirectToAction("ThemeSub");
        }

        [HttpPost]
        public ActionResult CancelTheme()
        {
            var temaID = Request.Form.Get("TemaID");
            Tema tema = db.Teme.Find(Int32.Parse(temaID));
            // dodaj autora u korisnikove pretplate (trenutnog)
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            if (ModelState.IsValid)
            {
                korisnik.Teme.Remove(tema);
                db.SaveChanges();
            }
            return RedirectToAction("ThemeSub");
        }

        // GET : Subscription/Membership
        public ActionResult Membership()
        {
            return View();
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        // POST: Subscription/Membership
        [HttpPost]
        public ActionResult Membership(FormCollection collection)
        {
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var id = User.Identity.GetUserId();
                var roles=UserManager.GetRoles(id);
                UserManager.RemoveFromRoles(id,"Simpatizer");
                if (!User.IsInRole("Clan"))
                {
                    UserManager.AddToRole(id, "Clan");
                }
                String pret=Request.Form.Get("Pretplata");
                Clanstvo clanstvo = new Clanstvo();
                id = User.Identity.GetUserId();
                ApplicationUser user = ApplicationDbContext.Users.Find(id);
                Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
                clanstvo.KorisnikID = korisnik.KorisnikID;
                clanstvo.DatumPlat = DateTime.Now;
                if (pret == "month")
                {
                if (korisnik.Clanstva.Count()==0)
                {
                    clanstvo.DatumIstek = DateTime.Now.AddMonths(1);
                } else
                {
                    clanstvo.DatumIstek=korisnik.Clanstva.First().DatumIstek.AddMonths(1);
                }
                } else
                {
                if (korisnik.Clanstva.Count()==0)
                {
                    clanstvo.DatumIstek = DateTime.Now.AddYears(1);

NaseSlovoApp/Views/Subscription/AllSub.cshtml
@{
    ViewBag.Title = "AllSub";
}
<!--Hardkodirano. Nisam našo bolji način reusea zasad-->
<h1>Sve pretplate</h1><br /><br />
<h2>Pretplate na autora</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <a href="http://localhost:63774/Article/Top">Ivo Andrić</a>
    </fieldset>
</form>
<br />
<h2>Pretplate na temu</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <a href="http://localhost:63774/Article/Top">Drama</a><br />
        <a href="http://www.9gag.com">Komedija</a>
    </fieldset>
</form><br />
<h2>Pretplate na tip</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <a href="http://localhost:63774/Article/Top">Roman</a><br />
        <a href="#">Proza<a>
    </fieldset>
</form>

NaseSlovoApp/Views/Subscription/AuthorSub.cshtml
@model IEnumerable<NaseSlovoApp.Models.Korisnik>

@{
    ViewBag.Title = "AuthorSub";
}
<h2>Pretplate na autora</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <div class="col-sm-8 page-content">
            <!--Ovdje ubaciti for petlju i povući članke iz baze-->

            @foreach (var item in Model.ToList())
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default panel-horizontal">
                            <div class="panel-body">

                                <div>
                                    <a class="panel-title" href="#">@Html.DisplayFor(modelItem => item.Ime) @Html.DisplayFor(modelItem => item.Prezime)</a>
                                </div>
                                @if (ViewBag.pret.Contains(item.KorisnikID))
                                {
                                    using (Html.BeginForm("CancelAuthor", "Subscription", FormMethod.Post, new { id = "Form Name" }))
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="KorisnikID" value="@item.KorisnikID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Otkaži pretplatu" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    using (Html.BeginForm())
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="KorisnikID" value="@item.KorisnikID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Pretplati se" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        </div>

                    </div>
                </div>
            }
            <!--Poboljsati footer-->
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>


        </div>

    </fieldset>
</form>

NaseSlovoApp/Views/Subscription/Index.cshtml
@{
    ViewBag.Title = "Sve pretplate";
}

<h2>Sve pretplate</h2>

NaseSlovoApp/Views/Subscription/Membership.cshtml
@{
    ViewBag.Title = "Membership";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h1>Načini pretplate:</h1>
        <select name="Pretplata">
            <option value="month">
                Mjesečno
            </option>
            <option value="year">
                Godišnje
            </option>
        </select>
        <span>
            <!--dodati onclick na gumb da bude koristan ;) .-->
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Potvrdi" class="btn btn-default" style="border-color:#c62828  ; background-color:#b71c1c ; border-radius:3px ; color:white" />
                </div>
            </div>
            <!--style="border-color:#c62828  ; background-color:#b71c1c ; border-radius:3px"-->
        </span>
    </div>
}

NaseSlovoApp/Views/Subscription/Options.cshtml
@model NaseSlovoApp.Models.Korisnik
@{
    ViewBag.Title = "Options";
}

<h2>Postavke</h2>
<!--Ubaciti podatke iz baze-->
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Postavke</h4>
        <div class="form-group">
            @Html.LabelFor(model => model.Ime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Ime, new { @class = "form-control" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Prezime, new { @class = "form-control" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @readonly = "readonly" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Spol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.TextBoxFor(model => model.Spol, new { @class = "form-control" })

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ažuriraj" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<br /> @if (ViewBag.role)
{
    <a href="@Url.Action("Membership", "Subscription")"><i class="fa fa-user-plus" aria-hidden="true"></i> Učlani se</a>
}
else
{
    if (ViewBag.isteklo)
    {
        <h2>Članarina je istekla!</h2>
        <a href="@Url.Action("Membership", "Subscription")"><i class="fa fa-user-plus" aria-hidden="true"></i> Učlani se</a>
    }
    else
    {
        if (ViewBag.istek != null)
        {
        <div class="text-danger">Članarina vam ističe: @ViewBag.istek</div>
        }
        <a href="@Url.Action("Membership", "Subscription")"><i class="fa fa-user-plus" aria-hidden="true"></i> Produlji članstvo</a>
    }
}

    @Html.AntiForgeryToken()
    @Html.Hidden("KorisnikID", Html.DisplayFor(model => model.KorisnikID)) <br />
    @Html.ActionLink("Izbriši profil", "Delete", "Korisnici",new { id = Model.KorisnikID },null)

NaseSlovoApp/Views/Subscription/ThemeSub.cshtml
@model IEnumerable<NaseSlovoApp.Models.Tema>

@{
    ViewBag.Title = "ThemeSub";
}
<h2>Pretplate na temu</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <div class="col-sm-8 page-content">
            <!--Ovdje ubaciti for petlju i povući članke iz baze-->

            @foreach (var item in Model.ToList())
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default panel-horizontal">
                            <div class="panel-body">

                                <div>
                                    <a class="panel-title" href="#">@Html.DisplayFor(modelItem => item.Naziv)</a>
                                </div>
                                @if (ViewBag.pret.Contains(item.TemaID))
                                {
                                    using (Html.BeginForm("CancelTheme", "Subscription", FormMethod.Post, new { id = "Form Name" }))
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="TemaID" value="@item.TemaID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Otkaži pretplatu" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    using (Html.BeginForm())
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="TemaID" value="@item.TemaID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Pretplati se" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        </div>

                    </div>
                </div>
            }
            <!--Poboljsati footer-->
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>


        </div>

    </fieldset>
</form>

NaseSlovoApp/Views/Subscription/TypeSub.cshtml
@model IEnumerable<NaseSlovoApp.Models.Vrsta>

@{
    ViewBag.Title = "TypeSub";
}
<h2>Pretplate na vrstu</h2>
<form>
    <fieldset>
        <legend>Trenutno ste pretplaćeni na:</legend>
        <div class="col-sm-8 page-content">
            <!--Ovdje ubaciti for petlju i povući članke iz baze-->

            @foreach (var item in Model.ToList())
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default panel-horizontal">
                            <div class="panel-body">

                                <div>
                                    <a class="panel-title" href="#">@Html.DisplayFor(modelItem => item.Naziv)</a>
                                </div>
                                @if (ViewBag.pret.Contains(item.VrstaID))
                                {
                                    using (Html.BeginForm("CancelType", "Subscription", FormMethod.Post, new { id = "Form Name" }))
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="VrstaID" value="@item.VrstaID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Otkaži pretplatu" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                                else
                                {
                                    using (Html.BeginForm())
                                    {

                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="VrstaID" value="@item.VrstaID"></input>
                                        <div class="form-horizontal">
                                            <div class="form-group">
                                                <div class="col-md-offset-2 col-md-10">
                                                    <input type="submit" value="Pretplati se" class="btn btn-outline btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }
                            </div>
                        </div>

                    </div>
                </div>
            }
            <!--Poboljsati footer-->
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>


        </div>

    </fieldset>
</form>