NaseSlovoApp/Controllers/TekstoviController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NaseSlovoApp.Models;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using System.IO;

namespace NaseSlovoApp.Controllers
{

    public class TekstoviController : Controller
    {
        private DatabaseEntities db = new DatabaseEntities();

        protected ApplicationDbContext ApplicationDbContext { get; set; }

        protected UserManager<ApplicationUser> UserManager { get; set; }

        public TekstoviController()
        {
            this.ApplicationDbContext = new ApplicationDbContext();
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
        }

        // GET: Tekstovi
        public ActionResult Index(int? page)
        {
            // TODO Roles.GetRolesForUser ne radi
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            if (!User.IsInRole("Clan") && !User.IsInRole("Autor") && !User.IsInRole("Urednik") && !User.IsInRole("Lektor") && !User.IsInRole("GrafickiUrednik"))
            {
                tekstovi = tekstovi.Where(t => !t.Privatan);
            }
            tekstovi = tekstovi.Where(t => t.Objavljen)
                .OrderByDescending(t => t.DatumVrijeme);

            //int pageSize = (int)Math.Ceiling((double)tekstovi.Count() / 10);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekstovi.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Search(string searchString, int? page)
        {
            var tekstovi = from t in db.Tekstovi
                           select t;
            // ili samo db.tekstovi ?
            if (!String.IsNullOrEmpty(searchString))
            {
                page = 1;
                // pretrazivanje po naslovu
                tekstovi = tekstovi
                    .Where(s => s.Naslov.Contains(searchString))
                    .Where(t => t.Objavljen);

                if (!User.IsInRole("Clan") && !User.IsInRole("Autor") && !User.IsInRole("Urednik") && !User.IsInRole("Lektor") && !User.IsInRole("GrafickiUrednik"))
                {
                    tekstovi = tekstovi.Where(t => !t.Privatan);
                }
            }

            ViewBag.SearchString = searchString;

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekstovi.OrderByDescending(t => t.DatumVrijeme).ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Top(int? page)
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            // rangiraj po srednjoj ocjeni i odaberi prvih 10
            tekstovi = tekstovi
                .Where(t => t.Objavljen)
                .OrderByDescending(t => t.SrednjaOcjena)
                .Take(10);

            if (!User.IsInRole("Clan") && !User.IsInRole("Autor") && !User.IsInRole("Urednik") && !User.IsInRole("Lektor") && !User.IsInRole("GrafickiUrednik"))
            {
                tekstovi = tekstovi.Where(t => !t.Privatan)
                    .OrderByDescending(t => t.SrednjaOcjena);
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekstovi.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Neobjavljeno(int? page)
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            // rangiraj po srednjoj ocjeni i odaberi prvih 10
            tekstovi = tekstovi
                .Where(t => t.Objavljen == false)
                .OrderByDescending(t => t.DatumVrijeme);

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekstovi.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Pretplate(int? page)
        {
            string id = User.Identity.GetUserId();
            ApplicationUser user = ApplicationDbContext.Users.Find(id);
            Korisnik korisnik = db.Korisnici.Find(user.KorisnikID);
            var tekstovi = db.Tekstovi;
            var autori = korisnik.Autori;
            var vrste = korisnik.Vrste;
            var teme = korisnik.Teme;
            List<Tekst> tekst = new List<Tekst>();
            foreach (Tekst item in tekstovi)
            {
                if ((vrste.Contains(item.Vrsta) || teme.Contains(item.Tema) || autori.Contains(item.Korisnik)) && item.Objavljen)
                {
                    tekst.Add(item);
                }
            }
            //tekst.Sort();

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekst.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Files/"), file.FileName);

            var data = new byte[file.ContentLength];
            file.InputStream.Read(data, 0, file.ContentLength);
            using (var sw = new FileStream(path, FileMode.Create))
            {
                sw.Write(data, 0, data.Length);

            }
            var fileContents = System.IO.File.ReadAllText(Server.MapPath("~/Content/Files/" + file.FileName));
            TempData["tekst"] = fileContents.ToString();
            return RedirectToAction("Create");
        }

        // GET
        public ActionResult UrediBilten()
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            // rangiraj po srednjoj ocjeni i odaberi prvih 10
            tekstovi = tekstovi
                .Where(t => t.Objavljen)
                .Where(t => !t.Privatan)
                .Where(t => t.DatumVrijeme.Month == DateTime.Now.Month
                && t.DatumVrijeme.Year == DateTime.Now.Year)
                .OrderByDescending(t => t.SrednjaOcjena)
                .Take(10)
                .Where(t => !t.Odabran);
            
            return View("UrediBilten", tekstovi.ToList());
        }

        // POST
        [HttpPost]
        public ActionResult UrediBilten(List<Tekst> nista)
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            // rangiraj po srednjoj ocjeni i odaberi prvih 10
            tekstovi = tekstovi
                .Where(t => t.Objavljen)
                .Where(t => !t.Privatan)
                .Where(t => t.DatumVrijeme.Month == DateTime.Now.Month
                && t.DatumVrijeme.Year == DateTime.Now.Year)
                .OrderByDescending(t => t.SrednjaOcjena)
                .Take(10);

            foreach (Tekst tekst in tekstovi)
            {
                tekst.Odabran = true;
            }
            db.SaveChanges();

            return View("UrediBilten", tekstovi.ToList());
        }

        // GET
        public ActionResult UrediBiltenOdabrani(int? page)
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            tekstovi = tekstovi
                .Where(t => t.Objavljen)
                .Where(t => !t.Privatan)
                .Where(t => t.Odabran)
                .Where(t => t.DatumVrijeme.Month == DateTime.Now.Month
                && t.DatumVrijeme.Year == DateTime.Now.Year)
                .OrderByDescending(t => t.SrednjaOcjena);

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View("All", tekstovi.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Bilten()
        {
            // ako ima u bazi s trenutnim mjesecom i godinom
            if (db.Bilteni.Where(b => b.Datum.Month == DateTime.Now.Month
            && b.Datum.Year == DateTime.Now.Year).Count() > 0)
            {
                // 
                string datum = DateTime.Now.Month.ToString() + "-" + DateTime.Now.Year.ToString();
                var srcFile = Server.MapPath("~/Content/Files/bilten" + datum + ".pdf");
                //string contents = System.IO.File.ReadAllText(srcFile);
                var destFile = Server.MapPath("~/App_Data/bilten" + datum + ".pdf");
                //System.IO.File.WriteAllText(destFile, contents);
                System.IO.File.Copy(srcFile, destFile);
            }
            
            // preuzmi
            return RedirectToAction("Index");
        }

        public ActionResult Zbornik()
        {
            var tekstovi = db.Tekstovi.Include(t => t.Korisnik).Include(t => t.Tema).Include(t => t.Vrsta);
            tekstovi = tekstovi
                .Where(t => t.Objavljen)
                .Where(t => !t.Privatan)
                .Where(t => t.DatumVrijeme.Year == DateTime.Now.Year);

            var zbornikTekstovi = new List<Tekst>();
            for (int month=1; month<=12; ++month)
            {
                var top = tekstovi
                    .Where(t => t.DatumVrijeme.Month == month)
                    .OrderByDescending(t => t.SrednjaOcjena);
                if (top.Count() == 0) continue;
                var tekst = top.Take(1).First();
                zbornikTekstovi.Add(tekst);
            }

            return View(zbornikTekstovi);
        }

        // GET
        public ActionResult PostaviBilten()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PostaviBilten(HttpPostedFileBase file)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Files/"), file.FileName);

            var data = new byte[file.ContentLength];

NaseSlovoApp/Views/Tekstovi/All.cshtml
@model PagedList.IPagedList<NaseSlovoApp.Models.Tekst>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "All";
}

<div class="container-fluid text-center">
        <div class="col-sm-8 page-content">
            <!--Ovdje ubaciti for petlju i povući članke iz baze-->

            @foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default panel-horizontal">
                                <div class="panel-body">
                                    <div>
                                        <img class="profile-small" src="http://www.pngall.com/wp-content/uploads/2016/05/Pen.png">
                                        @Html.ActionLink(item.Korisnik.Ime+" "+item.Korisnik.Prezime, "Details", "Korisnici", new { id = item.Korisnik.KorisnikID }, null)
                                        <span class="date">@Html.DisplayFor(modelItem => item.DatumVrijeme)</span>
                                    </div>
                                    <div>
                                        <a class="panel-title" href="#">@Html.DisplayFor(modelItem => item.Naslov)</a>
                                    </div>
                                    <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(modelItem => item.Tema.Naziv)</button>
                                    <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(modelItem => item.Vrsta.Naziv)</button>
                                    <hr>
                                    @Html.DisplayFor(modelItem => item.Sadrzaj)
                                    @Html.ActionLink("Procitaj tekst", "Details", "Tekstovi", new { id = item.TekstID }, null)
                                </div>
                                <div class="panel-footer">
                                    <span class="score">@Html.DisplayFor(modelItem => item.SrednjaOcjena)/10</span>
                                </div>
                            </div>

                        </div>
                    </div>
                }
            <!--Poboljsati footer-->
            <footer style="background-color:rgba(0,0,0,0)">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchString = ViewBag.SearchString }))
                
            </footer>


        </div>
    </div>


<script type="text/javascript">

  var element_position = $('.sideright').offset().top;
  var is_fixed = false;
  $('#close-not').click(function () {
    $('.navbar-notification').remove();
  });

  $(window).on('scroll', function() {
      var y_scroll_pos = window.pageYOffset;
      var scroll_pos_test = element_position;

      if(y_scroll_pos > scroll_pos_test && is_fixed == false) {


          $('.side-fixed-off').attr('class','side-fixed');
          is_fixed = true;

      }
      if(y_scroll_pos < scroll_pos_test && is_fixed == true) {
          $('.side-fixed').attr('class','side-fixed-off');
          is_fixed = false;
      }
  });

</script>

NaseSlovoApp/Views/Tekstovi/Create.cshtml
@model NaseSlovoApp.Models.Tekst

@{
    ViewBag.Title = "Novi tekst";
}

<h2>@ViewBag.Title</h2>

@{ 
    string tekst = null;
    if (TempData["tekst"] != null)
    {
        tekst =(string) TempData["tekst"];
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tekst</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Sadrzaj, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (tekst != null)
                {
                    <textarea class = "form-control">@tekst.ToString()</textarea>
                }
                else
                {
                @Html.TextAreaFor(model => model.Sadrzaj,10,100, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sadrzaj, "", new { @class = "text-danger" })
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naslov, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naslov, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TemaID, "TemaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TemaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TemaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrstaID, "VrstaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VrstaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VrstaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pošalji" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @using (Html.BeginForm("Upload", "Tekstovi", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="File" name="file" id="file" value="Izaberite datoteku" />
        <button type="submit">Upload</button>
    }
</div>

<div>
    @Html.ActionLink("Nazad na tekstove", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NaseSlovoApp/Views/Tekstovi/Details.cshtml
@model NaseSlovoApp.Models.Tekst

@{
    ViewBag.Title = "Details";
}

@{
    var result = "";
    if (IsPost)
    {
        var firstName = Request["FirstName"];

        var naslov = Model.Naslov;
        var sadrzaj = Model.Sadrzaj;
        var tekst = naslov + Environment.NewLine + Environment.NewLine + sadrzaj;

        var dataFile = Server.MapPath("~/App_Data/" + naslov + ".txt");
        File.WriteAllText(@dataFile, tekst);
        result = "Datoteka je preuzeta u folder App_Data.";
    }
}

@{
    bool hasRight = (bool)ViewData["HasRight"];
    bool objavljen = (bool)ViewData["Objavljen"];
    bool privatan = (bool)ViewData["Privatan"];
}


<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">@Html.DisplayFor(model => model.Naslov)</h1>
        <p class="text-info">@Html.DisplayFor(model => model.DatumVrijeme) </p>
        <p>Autor: <span class="text-info">@Html.DisplayFor(model => model.Korisnik.Ime) @Html.DisplayFor(model => model.Korisnik.Prezime)</span></p>
    </div>

    <!-- sadrzaj -->
    <div class="col-sm-8 blog-main">
        <div class="blog-post">
            <p class="blog-post-meta">
                <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(model => model.Tema.Naziv)</button>
                <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(model => model.Vrsta.Naziv)</button>
            </p>
            <p>
                @Html.DisplayFor(model => model.Sadrzaj)
            </p>
            <br />
        </div>

        <!-- ocjena -->
        <table class="table table-striped table-hover">
            <tr class="info"></tr>
            <tr class="danger">
                <td><h5><b>Srednja ocjena:</b></h5></td>
                <td class="col-md-offset-2" style="text-align: right;"><h4><b>@Html.DisplayFor(model => model.SrednjaOcjena) / 10</b></h4></td>
            </tr>
            @if (hasRight)
            {
                <tr class="danger">
                    <td><h5>Moja ocjena:</h5></td>
                    <td class="col-md-4" style="text-align: right;">

                        @using (Html.BeginForm("Create", "OcjeneTekstova", FormMethod.Post, new { id = "Form Name" }))
                {
                            @Html.AntiForgeryToken()

                            @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));

                            <div class="form-inline">
                                <div class="form-group">
                                    <div style="width: 100%;">
                                        @Html.DropDownList("Ocjena", new List<SelectListItem>
                 {
                    new SelectListItem{ Text="1", Value = "1" },
                    new SelectListItem{ Text="2", Value = "2" },
                    new SelectListItem{ Text="3", Value = "3" },
                    new SelectListItem{ Text="4", Value = "4" },
                    new SelectListItem{ Text="5", Value = "5" },
                    new SelectListItem{ Text="6", Value = "6" },
                    new SelectListItem{ Text="7", Value = "7" },
                    new SelectListItem{ Text="8", Value = "8" },
                    new SelectListItem{ Text="9", Value = "9" },
                    new SelectListItem{ Text="10", Value = "10" }
                 }, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-6">
                                        <input type="submit" class="btn btn-default" value="Ocijeni" />
                                    </div>
                                </div>
                            </div>
                        }

                    </td>
                </tr>
            }
        </table>

        <!-- download -->
        <form id="form_download" method="post" class="form-inline">
            <div class="form-group col-xs-10">
                <input type="submit" class="btn btn-default" value="Preuzmi" />
                @if (result != "")
                {
                    <p>@result</p>
                }

            </div>
        </form>

        <!-- urednik -->
        @if (User.IsInRole("Urednik"))
        {
            if (!objavljen)
            {
                using (Html.BeginForm("Details", "Tekstovi", FormMethod.Post, new { id = "Form name" }))
                {
                    @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));

                    <div class="form-inline">
                        <div class="form-group">
                            <div class="col-xs-10 form-inline">
                                <input type="submit" class="btn btn-default" value="Prihvati" name="decision"
                                       style="float:left" />
                                <input type="submit" class="btn btn-default" value="Odbij" name="decision"
                                       style="float:left; width:100%; overflow:auto; display:block" />
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="form-inline">
                    @using (Html.BeginForm("Del", "Tekstovi", FormMethod.Post, new { id = "Form name" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));
                        <div class="form-group">
                            <div class="col-xs-10">
                                <input type="submit" class="btn btn-default" value="Izbriši tekst" name="delete" />
                            </div>
                        </div>
                    }

                    @using (Html.BeginForm("Details", "Tekstovi", FormMethod.Post, new { id = "Form name" }))
                    {
                        @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));
                        <div class="form-group">
                            <div class="col-xs-10">
                                <select name="privatan">
                                    <option value="privatan">Privatan</option>
                                    <option value="javan">Javan</option>
                                </select>
                                <span><input type="submit" class="btn btn-default" value="Potvrdi" name="delete" /></span>
                            </div>
                        </div>
                    }
                </div>
            }
        }

        @if (User.IsInRole("Urednik") || User.IsInRole("Lektor"))
        {
            <h2>Lektorov komentar</h2>
            @Html.DisplayFor(modelItem => modelItem.LektorovKomentar)<br />
        }

        <h2>Komentari</h2>
        @foreach (var item in Model.Komentari)
        {
            <div class="row">
                <div class="col-lg-5">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <strong>@Html.DisplayFor(modelItem => item.Korisnik.KorisnickoIme)</strong>
                            <span class="text-muted">@Html.DisplayFor(modelItem => item.DatumVrijeme)</span>
                        </div>
                        <div class="panel-body">
                            @Html.DisplayFor(modelItem => item.Sadrzaj)
                        </div><!-- /panel-body -->
                    </div><!-- /panel panel-default -->
                </div><!-- /col-sm-5 -->
            </div>
        }

        @if (User.IsInRole("Lektor") && !objavljen)
        {
            using (Html.BeginForm("LektorKom", "Komentari", FormMethod.Post, new { id = "Form Name" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));
                <div class="form-horizontal">
                    <h4>Lektorski komentar</h4>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Sadrzaj, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <!-- TODO sadrzaj makni, model komentara ne teksta-->

                            @Html.TextAreaFor(model => model.Sadrzaj, new { htmlAttributes = new { @class = "form-control", @Value = "Unesite komentar" } })
                            @Html.ValidationMessageFor(model => model.Sadrzaj, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Komentiraj" class="btn btn-default" />
                        </div>
                    </div>

                </div>
            }
        }
        else
        {
            <!-- ostali -->
            using (Html.BeginForm("Create", "Komentari", FormMethod.Post, new { id = "Form Name" }))
            {
                @Html.AntiForgeryToken()

                @Html.Hidden("TekstID", @Html.DisplayFor(model => model.TekstID));

                <div class="form-horizontal">
                    <div class="form-group">
                        <h4>Dodaj novi komentar</h4>

                        <!-- Html.LabelFor(model => model.Sadrzaj, htmlAttributes: new { class = "control-label col-md-2" }) -->

                        <div class="col-md-10">

                            @Html.TextAreaFor(model => model.Sadrzaj, 10, 100, new { htmlAttributes = new { @class = "form-control" } })

                            @Html.ValidationMessageFor(model => model.Sadrzaj, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="submit" value="Komentiraj" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        }

    </div>
</div>

NaseSlovoApp/Views/Tekstovi/PostaviBilten.cshtml
@{
    ViewBag.Title = "PostaviBilten";
}

<h2>PostaviBilten</h2>

<div>
    @using (Html.BeginForm("PostaviBilten", "Tekstovi", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="File" name="file" id="file" value="Izaberite datoteku" />
        <button type="submit">Upload</button>
    }
</div>

NaseSlovoApp/Views/Tekstovi/UrediBilten.cshtml
@model IEnumerable<NaseSlovoApp.Models.Tekst>

@{
    ViewBag.Title = "Bilten";
}

<div class="container-fluid text-center">
        <div class="col-sm-8 page-content">
            <!--Ovdje ubaciti for petlju i povući članke iz baze-->

            @foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <div class="panel panel-default panel-horizontal">
                                <div class="panel-body">
                                    <div>
                                        <img class="profile-small" src="https://placekitten.com/60/50">
                                        @Html.ActionLink(item.Korisnik.Ime+" "+item.Korisnik.Prezime, "Details", "Korisnici", new { id = item.Korisnik.KorisnikID }, null)
                                        <span class="date">@Html.DisplayFor(modelItem => item.DatumVrijeme)</span>
                                    </div>
                                    <div>
                                        <a class="panel-title" href="#">@Html.DisplayFor(modelItem => item.Naslov)</a>
                                    </div>
                                    <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(modelItem => item.Tema.Naziv)</button>
                                    <button type="button" class="btn btn-outline btn-primary">@Html.DisplayFor(modelItem => item.Vrsta.Naziv)</button>
                                    <hr>
                                    @Html.DisplayFor(modelItem => item.Sadrzaj)
                                    @Html.ActionLink("Procitaj tekst", "Details", "Tekstovi", new { id = item.TekstID }, null)
                                </div>
                                <div class="panel-footer">
                                    <span class="score">@Html.DisplayFor(modelItem => item.SrednjaOcjena)/10</span>
                                </div>
                            </div>

                        </div>
                    </div>
                }

            <!-- potvrdi bilten -->
            @if (User.IsInRole("GlavniUrednik"))
            {
                if (Model.Count() == 0)
                {
                    <h2>Već ste odabrali tekstove za ovaj mjesec</h2>

                    <p>Objavi bilten na webu:</p><br />

                    using (Html.BeginForm("PostaviBiltenUrednik", "Tekstovi", FormMethod.Post, new { id = "form name" }))
                    {
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn btn-default" value="Objavi" />
                            </div>
                        </div>
                    }

                }
                else
                {
                    using (Html.BeginForm("UrediBilten", "Tekstovi", FormMethod.Post, new { tekstovi = Model }))
                    {
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" class="btn btn-default" value="Potvrdi" name="decision" />
                        </div>
                    </div>
                    }
                }
            }

    </div>
</div>

<script type="text/javascript">

  var element_position = $('.sideright').offset().top;
  var is_fixed = false;
  $('#close-not').click(function () {
    $('.navbar-notification').remove();
  });

  $(window).on('scroll', function() {
      var y_scroll_pos = window.pageYOffset;
      var scroll_pos_test = element_position;

      if(y_scroll_pos > scroll_pos_test && is_fixed == false) {


          $('.side-fixed-off').attr('class','side-fixed');
          is_fixed = true;

      }
      if(y_scroll_pos < scroll_pos_test && is_fixed == true) {
          $('.side-fixed').attr('class','side-fixed-off');
          is_fixed = false;
      }
  });

</script>