NaseSlovoApp/Controllers/KorisniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NaseSlovoApp.Models;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;

namespace NaseSlovoApp.Controllers
{
	public class KorisniciController : Controller
	{
		private DatabaseEntities db = new DatabaseEntities();

		protected ApplicationDbContext ApplicationDbContext { get; set; }

		protected UserManager<ApplicationUser> UserManager { get; set; }

		public KorisniciController()
		{
			this.ApplicationDbContext = new ApplicationDbContext();
			this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.ApplicationDbContext));
		}

		// GET: Korisnici
		public ActionResult Index()
		{
			return View(db.Korisnici.ToList());
		}
		
		public ActionResult Clanovi()
		{
			var korisnici = db.Korisnici.Where(u => u.Clanstva.Count != 0);
			
			return View(korisnici.ToList());
		}

		public ActionResult DodijeliAutora(int id)
		{
			Korisnik korisnik = db.Korisnici.Find(id);
			korisnik.Autor = !korisnik.Autor;
			db.SaveChanges();
			return RedirectToAction("Clanovi");
		}

		// GET: Korisnici/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Korisnik korisnik = db.Korisnici.Find(id);
			if (korisnik == null)
			{
				return HttpNotFound();
			}
			return View(korisnik);
		}

		// GET: Korisnici/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Korisnici/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "KorisnikID,Ime,Prezime,DatumRod,Email,Spol")] Korisnik korisnik)
		{
			if (ModelState.IsValid)
			{
				db.Korisnici.Add(korisnik);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(korisnik);
		}

		// GET: Korisnici/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Korisnik korisnik = db.Korisnici.Find(id);
			if (korisnik == null)
			{
				return HttpNotFound();
			}
			return View(korisnik);
		}

		private IAuthenticationManager AuthenticationManager
		{
			get
			{
				return HttpContext.GetOwinContext().Authentication;
			}
		}

		// POST: Korisnici/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "KorisnikID,Ime,Prezime,DatumRod,Email,Spol")] Korisnik korisnik)
		{
			if (ModelState.IsValid)
			{
				db.Entry(korisnik).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(korisnik);
		}

		// GET: Korisnici/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Korisnik korisnik = db.Korisnici.Find(id);
			if (korisnik == null)
			{
				return HttpNotFound();
			}
			return View(korisnik);
		}

		// POST: Korisnici/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Korisnik korisnik = db.Korisnici.Find(id);
			db.Korisnici.Remove(korisnik);
			db.SaveChanges();
			AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
			ApplicationUser user = ApplicationDbContext.Users.Where(u => u.KorisnikID == id).First();
			UserManager.Delete(user);
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

NaseSlovoApp/Views/Korisnici/Clanovi.cshtml
@model IEnumerable<NaseSlovoApp.Models.Korisnik>

@{
    ViewBag.Title = "Index";
    string text = "";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumRod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Spol)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatumRod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Spol)
        </td>
        <td>
            @if (item.Autor)
            {
                text = "Makni status autora";
            }
            else
            {
                text = "Dodijeli status autora";
            }
            @Html.ActionLink(text, "DodijeliAutora", "Korisnici", new { id = item.KorisnikID }, null)
        </td>
    </tr>
}

</table>

NaseSlovoApp/Views/Korisnici/Create.cshtml
@model NaseSlovoApp.Models.Korisnik

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Korisnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Spol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Spol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Spol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NaseSlovoApp/Views/Korisnici/Delete.cshtml
@model NaseSlovoApp.Models.Korisnik

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Spol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Spol)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NaseSlovoApp/Views/Korisnici/Details.cshtml
@model NaseSlovoApp.Models.Korisnik

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Korisnik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Spol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Spol)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.KorisnikID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NaseSlovoApp/Views/Korisnici/Edit.cshtml
@model NaseSlovoApp.Models.Korisnik

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Korisnik</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.KorisnikID)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Spol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Spol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Spol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NaseSlovoApp/Views/Korisnici/Index.cshtml
@model IEnumerable<NaseSlovoApp.Models.Korisnik>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DatumRod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Spol)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DatumRod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Spol)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.KorisnikID }) |
            @Html.ActionLink("Details", "Details", new { id=item.KorisnikID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.KorisnikID })
        </td>
    </tr>
}

</table>